### ISSUE TITLE
error message when I create the accredible certificate in moodle 3.6

### ISSUE THREAD

**Issue by soonho2** [accredible/moodle-mod_accredible#11]
http://elearning.foodsecurityportal.org/course/modedit.php

Notice: Undefined variable: course in /opt/bitnami/apps/moodle/htdocs/mod/accredible/mod_form.php on line 42

Notice: Trying to get property of non-object in /opt/bitnami/apps/moodle/htdocs/mod/accredible/mod_form.php on line 42

Notice: Undefined variable: users_earned_certificate in /opt/bitnami/apps/moodle/htdocs/mod/accredible/mod_form.php on line 154

Notice: Undefined property: stdClass::$groupid in /opt/bitnami/apps/moodle/htdocs/mod/accredible/lib.php on line 40

Notice: Undefined variable: accredible_certificate in /opt/bitnami/apps/moodle/htdocs/mod/accredible/locallib.php on line 51

Notice: Trying to get property of non-object in /opt/bitnami/apps/moodle/htdocs/mod/accredible/locallib.php on line 51

Notice: Undefined property: stdClass::$completionactivities in /opt/bitnami/apps/moodle/htdocs/mod/accredible/lib.php on line 74

After that, there was group certificate

ID | Recipient | Certificate/Badge url | Date created
-- | -- | -- | --
14131394 | Betina Dimaranan | https://www.credential.net/b5b6928c-fd6e-478d-9520-dde3f4c2abaf | Nov 14, 2019
14131392 | Summer Allen | https://www.credential.net/e33ee433-93f6-4839-95e4-10270d2b28fd | Nov 14, 2019

Then, if I click the urls associated with users which I asigned for the certificate, I got this message
https://www.credential.net/error/404

**Comment by soonho2** [comment]
![error](https://user-images.githubusercontent.com/2243539/68892440-0d679a80-06f1-11ea-8702-c875030e6269.jpg)

**Comment by soonho2** [comment]
Could you kindly follow up? # #

**Comment by alanheppenstall** [comment]
This has been resolved in the latest version.
