### ISSUE TITLE
Exception - Using $this when not in object context

### ISSUE THREAD

**Issue by grantcolin** [accredible/moodle-mod_accredible#18]
Hi. We upgrade to :

Moodle Version : 3.10.1
Accredible Plugin Version : v1.6.2 (2020012701)

Now we get this error when we try to view certificates:

Exception - Using $this when not in object context
More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 9 of /mod/accredible/classes/client/client.php: Error thrown
line 30 of /mod/accredible/classes/apiRest/apiRest.php: call to mod_accredible\client\client::get()
line 109 of /mod/accredible/locallib.php: call to mod_accredible\apiRest\apiRest->get_credentials()
line 98 of /mod/accredible/view.php: call to accredible_get_credentials()
Output buffer: <br /> <b>Deprecated</b>: Non-static method mod_accredible\client\client::get() should not be called statically in <b>/mod/accredible/classes/apiRest/apiRest.php</b> on line <b>30</b><br />

**Comment by alanheppenstall** [comment]
Thanks @grantcolin - this is fixed in v1.6.3.
